### ISSUE TITLE
Training Procedure

### ISSUE THREAD

**Issue by shlomi-amitai** [jsczzzk/R-MSFM#3]
Hi,

Great work :)

Will you release the training procedure for this NN?

Thanks

**Comment by jsczzzk** [comment]
Hi, 
Sorry for the late reply. Our training procedure completely follows the [RAFT](https://github.com/princeton-vl/RAFT) and [Monodepth2](https://github.com/nianticlabs/monodepth2). The main differences between ours and monodepth2 are:
1. We only use the intrinsic camera parameters at full resolution during training instead of the multi-scale ones at the Monodepth2.
2. We give an update weight for each update of the self-supervision.

**Comment by harishkool** [comment]
What beta value (β) was used for training?

**Comment by jsczzzk** [comment]
In the 4.1. Implementation Details section, we state the update item β as 0.9.

**Comment by 9796l** [comment]
Excuse me,Will you upload the whole codes?I think your methods are significant.

**Comment by jsczzzk** [comment]
Hi, Thank you for your attention :) I am cleaning my code and will upload it in the future. Before then, you can refer to this [project](https://github.com/ZM-Zhou/SMDE-Pytorch), which achieves better results than mine.

**Comment by jsczzzk** [comment]
Now, you can train it with my code.
